### ISSUE TITLE
Why not expose `forAllT`

### ISSUE THREAD

**Issue by i-am-the-slime** [hedgehogqa/haskell-hedgehog#203] opened 2018-06-18 10:07 UTC
For some `a`, I have a `Gen IO a`.
I would like to write properties with these Generators, but I need to import the internal `forAllT` to get the test to compile.

What is the reasoning behind this?

**Comment by EarthCitizen** [comment] 2018-06-25 05:49
I was just about to open an issue for exactly the same thing! I need to embed `State` in `GenT`.

**Comment by EarthCitizen** [comment] 2018-06-25 07:37
Submitted pull request #206 to expose `forAllT` and `forAllWithT`.

**Comment by thumphries** [comment] 2018-06-25 21:13
I'm not sure if this was intentional or not! Trying to find out.

I use custom GenT stacks, but usually `hoist` them back to `Gen` to actually use them.

**Comment by EarthCitizen** [comment] 2018-06-26 07:38
@thumphries My pull request might be insufficient as it would mean that `sample` (hard-coded to `Identity`) would not work with a custom `GenT` stack. Without an API change, that would necessitate `sampleT`, etc., which may or may not be what you want for the API of the project.

The other option would be to simply expose `forAllT` and `forAllWithT`, leaving them without a `sample` and `print`. But, that does leave the API feeling incomplete.

The existing public API could potentially be changed to something like `Monad m => (GenT m) a` from `Gen a` without breaking existing code, since `Gen a` is just a type alias. It would be just allowing more types for `m`. Seems like it should be backwards compatible. It's a gray area if that should be considered an API change or not.

**Comment by werbitt** [comment] 2018-10-10 21:13
Hi @thumphries,

Could you give an example of how you would use hoist? 

For example if I have the following, how an I implement it using hoist instead of forAllT. 

```
genExample :: GenT IO Example
genExample = ...

prop_example :: Property
prop_example = property $ do
  ex <- forAllT genExample
  ex === ex
```

Thanks,
Micah

**Comment by thumphries** [comment] 2018-10-10 22:03
My code was using hedgehog-0.1 where this was possible, but with `type Gen = GenM Identity` I don't believe it is anymore without resorting to `hoist unsafePerformIO`.

Certainly seems like we should just export `forAllT`

**Comment by thumphries** [comment] 2018-10-10 22:05
The only remaining relevant code I have is along the lines of `GenM (ReaderT Something Identity)`, where `hoist runReaderT` is necessary.

If you feel like sharing, I'd love to hear how you're using IO generators. Use cases for them have been hard for us to come by

**Comment by werbitt** [comment] 2018-10-11 00:53
OK, cool, thank you for clearing that up and providing some examples of hoist in other contexts. 

In my case the generator is for random [wordfinds](https://en.wikipedia.org/wiki/Word_search). The wordfind is built in IO because it uses withSystemRandom from [mwc-random](https://hackage.haskell.org/package/mwc-random-0.13.6.0) to place words randomly in the wordfind, and also to fill in the voids with random characters.

Now that I think about it I have a lower level function that builds a wordfind in monad that is constrained by PrimMonad that I pass the prng into. It would probably make more sense of me to use that to generate the random wordfinds so I could provide a seed and make it more reproducible.

Thanks again.

**Comment by EarthCitizen** [comment] 2018-10-11 04:15
@thumphries Related issue #208.

**Comment by moodmosaic** [comment] 2018-11-06 09:34
Closing in favor of #208 which also points to https://github.com/hedgehogqa/haskell-hedgehog/pull/206#issuecomment-435702377 (both from @EarthCitizen).

**Closed by moodmosaic** 2018-11-06 09:34 UTC
Labels: question
