### ISSUE TITLE
`withTests` function doesn't work?

### ISSUE THREAD

**Issue by vrom911** [hedgehogqa/haskell-hedgehog#192] opened 2018-05-14 08:45 UTC
I want to limit the amount of tests in one property to some concrete number. The way I was trying to do so is
```haskell
myProperty :: Property
myProperty = withTests 5 $ property $ do 
  ...
  some checks
```
But it doesn't seem to work. Comparing to the property without  `withTests 5` there is no any difference. 

Is it a bug, or I'm not using this function properly? Also probably there is other way to restrict amount of tests?

**Comment by jystic** [comment] 2018-05-14 12:34
I'm sorry this isn't working for you, I use it myself quite a lot. The pseudocode above you have looks correct.

Messing around in ghci it seems to be doing the right thing:

```
λ check $ withTests 5 $ property $ 5 === 5
  ✓ <interactive> passed 5 tests.
True
λ check $ withTests 10 $ property $ 5 === 5
  ✓ <interactive> passed 10 tests.
True
```

Maybe there's more to the situation that we're missing here?

**Comment by jystic** [comment] 2018-05-14 13:11
Ah, that's certainly possible, maybe tasty is ignoring the hedgehog options in favour of its own way of setting the number of tests? Or maybe I've not made it possible for tasty to get hold of what it needs here.

@dalaing can you offer any insight on what might be going on?

**Comment by gwils** [comment] 2018-05-15 07:42
I've attempted to reproduce this and I can't do so. `withTests` seems to work fine for me.
Unfortunately `tasty-hedgehog` does not report how many times the tests were run, so maybe `withTests` is working fine for you, but since the info is missing, you can't tell.

Otherwise, maybe something is wrong with my reproduction attempt?
You can find it here: https://github.com/gwils/hedgehog-192-repro

**Comment by theindigamer** [comment] 2018-05-24 17:59
You could also specify the [HedgehogTestLimit](https://hackage.haskell.org/package/tasty-hedgehog-0.1.0.2/docs/Test-Tasty-Hedgehog.html#t:HedgehogTestLimit) as a Tasty option if you're using `tasty-hedgehog`.

**Comment by ChShersh** [comment] 2018-06-12 04:20
I created example reproducing this bug. Tests took the same amount of time with `withTests 1` and without this function call — approximately 9 seconds on my machine. I expect time to be very low when `withTests 1` is specified.

* https://github.com/ChShersh/hedgehog-192-example

**Comment by moodmosaic** [comment] 2018-06-13 03:58
It looks like it's tasty/tasty-* that ignores the Hedgehog options:

```
test\Spec.hs
  examplePropertyFoo: OK (0.10s)
    OK

All 1 tests passed (0.13s)
```

If I go and change the test driver file and set the number of tests

```diff
diff --git a/test/Spec.hs b/test/Spec.hs
index 70c55f5..74c7723 100644
--- a/test/Spec.hs
+++ b/test/Spec.hs
@@ -1 +1 @@
-{-# OPTIONS_GHC -F -pgmF tasty-discover #-}
+{-# OPTIONS_GHC -F -pgmF tasty-discover -optF --hedgehog-tests=100 #-}
```

then it takes longer to finish

```
test\Spec.hs
  examplePropertyFoo: OK (10.00s)
    OK

All 1 tests passed (10.00s)
```

Notice the first run, which finished in 0.13s, and the second run, which finished in 10.00s.

---

Perhaps it'll help to close this one and open an issue in tasty referencing this one.

**Comment by ChShersh** [comment] 2018-06-13 04:05
@vrom911 @moodmosaic Turned out it's the bug in `tasty-hedgehog`:

* https://github.com/qfpl/tasty-hedgehog/issues/9

As I can see it's already fixed and everything works as expected with newer versions of libraries. I was using `stack` and those versions of libraries. Turned out they have bug. I was confused by this...

**Closed** 2018-06-20 20:51 UTC
Labels: question
