### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/haskell-hedgehog#32] opened 2017-04-09 17:04 UTC
I've converted a couple of QuickCheck properties to Hedgehog and they seem to be running fine on macOS:

![image](https://cloud.githubusercontent.com/assets/287532/24839079/e89882c6-1d5c-11e7-9217-ea051e246680.png)

However, when I try to run the same tests on Windows I'm getting:

```
*** Exception: <stdout>: hPutChar: invalid argument (invalid character)
```

---

In case it helps to troubleshoot, I used

* [this](https://github.com/hedgehogqa/haskell-hedgehog/blob/cc3af0e1ed573f0c6c484b0b979535bbc068e336/hedgehog/src/Hedgehog.hs#L25-L27) Template Haskell splice to run the properties in both macOS and Windows
* GHC 8.0.2 on macOS and GHC 7.10.3 on Windows

**Comment by jystic** [comment] 2017-04-12 11:23
I suspect it's the unicode symbols? The colours and in-place updates should get disabled because they're checking [hSupportsANSI](https://hackage.haskell.org/package/ansi-terminal-0.6.2.3/docs/System-Console-ANSI.html#v:hSupportsANSI)

**Comment by hdgarrood** [comment] 2017-04-16 00:52
I think the fix for this is usually along the lines of running `hSetEncoding stderr utf8` before attempting to print to the console. At least I remember a similar bug being resolved in the purescript compiler that way.

**Comment by jystic** [comment] 2017-04-16 03:40
> I think the fix for this is usually along the lines of running `hSetEncoding stderr utf8` before attempting to print to the console.

Nice, I'll give that a shot

**Comment by moodmosaic** [comment] 2017-06-27 22:11
I *may* be able to give this a shot as well, over the next few weeks.

**Comment by thumphries** [comment] 2017-12-11 01:53
I *think* we can treat this as a dupe of #110 - the discussion there is a little more thorough, so let's keep that one open and close this. Reopen or file a more specific issue if more Windows problems emerge.

**Closed by thumphries** 2017-12-11 01:53 UTC
