### ISSUE TITLE
Odd exception-printing behavior

### ISSUE THREAD

**Issue by sellout** [hedgehogqa/haskell-hedgehog#386] opened 2020-06-09 01:17 UTC
We use Bazel for our build, and when I do `bazel run //my/test:target`, I get output like this
```
  ✗ wIndex failed at code/test/Main.hs:63:1
    after 1 test and 1 shrink.
    forAll0 =
      ( Identity '\NUL' , () )
    This failure can be reproduced by running:
    > recheck (Size 0) (Seed 4939657894023496209 18446526684814593677) wIndex
```
but if I run the executable directly `bazel-bin/code/test`, I get much better output:
```
  ✗ wIndex failed at code/test/Main.hs:63:1
    after 1 test and 1 shrink.
  
       ┏━━ code_generation/category/test/Test/Cat/ConCat/Main.hs ━━━
    63 ┃ mkAllTestTerms myTestStuff
       ┃ │ ( Identity '\NUL' , () )
       ┃ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       ┃ │ ━━━ Exception (PatternMatchFail) ━━━
       ┃ │ code/test/Cat.hs:406:17-37: Non-exhaustive patterns in lambda
  
    This failure can be reproduced by running:
    > recheck (Size 0) (Seed 1521430642105752216 5813173482663699645) wIndex
```
If it were just missing output, I would expect the fault is Bazel's but it seems like there's maybe something in Hedgehog that's affected by the environment it's run in or something? I don't know. Looking for any pointers here. Thanks.

**Comment by HuwCampbell** [comment] 2020-06-09 01:57
This looks like a bug to me.

I suspect that [this code path](https://github.com/hedgehogqa/haskell-hedgehog/blob/master/hedgehog/src/Hedgehog/Internal/Report.hs#L628-L630) is being exercised, but the file can't be found. So we're setting the mLocation to Nothing, while also not appending the exception to the messages.

**Comment by HuwCampbell** [comment] 2020-06-09 01:57
Likely duplicate of #379.

**Closed** 2020-06-17 08:32 UTC
